# Generated by Django 4.1.5 on 2023-02-27 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pravas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_booked', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duration', models.PositiveSmallIntegerField(help_text='Duration in days')),
                ('location', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='tour_images/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TourBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_booked', models.DateTimeField(auto_now_add=True)),
                ('num_adults', models.PositiveSmallIntegerField()),
                ('num_children', models.PositiveSmallIntegerField()),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pravas.tour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(upload_to='user_images/')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='date',
            new_name='travel_date',
        ),
        migrations.AddField(
            model_name='ticket',
            name='departure_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='mode',
            field=models.CharField(choices=[('Bus', 'Bus'), ('Train', 'Train'), ('Plane', 'Plane')], default='Bus', max_length=50),
        ),
        migrations.AddField(
            model_name='ticket',
            name='operators',
            field=models.CharField(default='GSRTC', max_length=50),
        ),
        migrations.AddField(
            model_name='ticket',
            name='total_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ticketbooking',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pravas.ticket'),
        ),
        migrations.AddField(
            model_name='ticketbooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
