# Generated by Django 4.1.5 on 2023-06-13 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="City",
        ),
    ]
