# Generated by Django 4.1.5 on 2023-03-31 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pravas', '0002_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='fSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('departure_time', models.TimeField()),
                ('total_time', models.TimeField()),
                ('price', models.IntegerField()),
                ('seat_class', models.CharField(blank=True, max_length=20)),
                ('fdestination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fdestination', to='pravas.city')),
                ('fsource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fsource', to='pravas.city')),
            ],
        ),
        migrations.CreateModel(
            name='fBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_booked', models.DateField()),
                ('seat_class', models.CharField(blank=True, max_length=20)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.flight')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.fseat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
