# Generated by Django 4.1.5 on 2023-02-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pravas', '0002_ticketbooking_tour_tourbooking_user_delete_booking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='travel_date',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='date_updated',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='destination',
            field=models.CharField(choices=[('Deesa', 'Deesa'), ('Navsari', 'Navsari'), ('Ahmedabad', 'Ahmedabad'), ('Mahesana', 'Mahesana'), ('Anand', 'Anand'), ('Rajkot', 'Rajkot'), ('Nadiad', 'Nadiad'), ('Jamnagar', 'Jamnagar'), ('Vadodara', 'Vadodara'), ('Surat', 'Surat'), ('Morbi', 'Morbi')], default='Ahmedabad', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='mode',
            field=models.CharField(choices=[('Plane', 'Plane'), ('Bus', 'Bus'), ('Train', 'Train')], default='Bus', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='source',
            field=models.CharField(choices=[('Deesa', 'Deesa'), ('Navsari', 'Navsari'), ('Ahmedabad', 'Ahmedabad'), ('Mahesana', 'Mahesana'), ('Anand', 'Anand'), ('Rajkot', 'Rajkot'), ('Nadiad', 'Nadiad'), ('Jamnagar', 'Jamnagar'), ('Vadodara', 'Vadodara'), ('Surat', 'Surat'), ('Morbi', 'Morbi')], default='Ahmedabad', max_length=50),
        ),
    ]
