# Generated by Django 4.1.5 on 2023-02-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pravas', '0005_alter_ticket_departure_time_alter_ticket_destination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_photo',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='destination',
            field=models.CharField(choices=[('Deesa', 'Deesa'), ('Anand', 'Anand'), ('Navsari', 'Navsari'), ('Rajkot', 'Rajkot'), ('Mahesana', 'Mahesana'), ('Nadiad', 'Nadiad'), ('Surat', 'Surat'), ('Morbi', 'Morbi'), ('Vadodara', 'Vadodara'), ('Ahmedabad', 'Ahmedabad'), ('Jamnagar', 'Jamnagar')], default='Ahmedabad', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='mode',
            field=models.CharField(choices=[('Bus', 'Bus'), ('Train', 'Train'), ('Plane', 'Plane')], default='Bus', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='operators',
            field=models.CharField(choices=[('Tulsi', 'Tulsi'), ('GSRTC', 'GSRTC'), ('Bharat', 'Bharat'), ('Kabra', 'Kabra')], default='GSRTC', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='source',
            field=models.CharField(choices=[('Deesa', 'Deesa'), ('Anand', 'Anand'), ('Navsari', 'Navsari'), ('Rajkot', 'Rajkot'), ('Mahesana', 'Mahesana'), ('Nadiad', 'Nadiad'), ('Surat', 'Surat'), ('Morbi', 'Morbi'), ('Vadodara', 'Vadodara'), ('Ahmedabad', 'Ahmedabad'), ('Jamnagar', 'Jamnagar')], default='Ahmedabad', max_length=50),
        ),
    ]
