# Generated by Django 4.1.5 on 2023-03-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pravas', '0007_ticketbooking_quantity_alter_ticket_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='destination',
            field=models.CharField(choices=[('Anand', 'Anand'), ('Nadiad', 'Nadiad'), ('Mahesana', 'Mahesana'), ('Ahmedabad', 'Ahmedabad'), ('Jamnagar', 'Jamnagar'), ('Vadodara', 'Vadodara'), ('Rajkot', 'Rajkot'), ('Surat', 'Surat'), ('Navsari', 'Navsari'), ('Deesa', 'Deesa'), ('Morbi', 'Morbi')], default='Ahmedabad', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='mode',
            field=models.CharField(choices=[('Bus', 'Bus'), ('Plane', 'Plane'), ('Train', 'Train')], default='Bus', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='operators',
            field=models.CharField(choices=[('Tulsi', 'Tulsi'), ('Bharat', 'Bharat'), ('GSRTC', 'GSRTC'), ('Kabra', 'Kabra')], default='GSRTC', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='source',
            field=models.CharField(choices=[('Anand', 'Anand'), ('Nadiad', 'Nadiad'), ('Mahesana', 'Mahesana'), ('Ahmedabad', 'Ahmedabad'), ('Jamnagar', 'Jamnagar'), ('Vadodara', 'Vadodara'), ('Rajkot', 'Rajkot'), ('Surat', 'Surat'), ('Navsari', 'Navsari'), ('Deesa', 'Deesa'), ('Morbi', 'Morbi')], default='Ahmedabad', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticketbooking',
            name='date_booked',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
