# Generated by Django 4.1.5 on 2023-03-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pravas', '0008_alter_ticket_destination_alter_ticket_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='destination',
            field=models.CharField(choices=[('Navsari', 'Navsari'), ('Nadiad', 'Nadiad'), ('Morbi', 'Morbi'), ('Rajkot', 'Rajkot'), ('Surat', 'Surat'), ('Ahmedabad', 'Ahmedabad'), ('Anand', 'Anand'), ('Mahesana', 'Mahesana'), ('Jamnagar', 'Jamnagar'), ('Vadodara', 'Vadodara'), ('Deesa', 'Deesa')], default='Ahmedabad', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='mode',
            field=models.CharField(choices=[('Train', 'Train'), ('Plane', 'Plane'), ('Bus', 'Bus')], default='Bus', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='operators',
            field=models.CharField(choices=[('Bharat', 'Bharat'), ('Tulsi', 'Tulsi'), ('Kabra', 'Kabra'), ('GSRTC', 'GSRTC')], default='GSRTC', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='source',
            field=models.CharField(choices=[('Navsari', 'Navsari'), ('Nadiad', 'Nadiad'), ('Morbi', 'Morbi'), ('Rajkot', 'Rajkot'), ('Surat', 'Surat'), ('Ahmedabad', 'Ahmedabad'), ('Anand', 'Anand'), ('Mahesana', 'Mahesana'), ('Jamnagar', 'Jamnagar'), ('Vadodara', 'Vadodara'), ('Deesa', 'Deesa')], default='Ahmedabad', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticketbooking',
            name='date_booked',
            field=models.DateField(auto_now=True),
        ),
    ]
