# Generated by Django 4.1.5 on 2023-03-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='banner',
            field=models.ImageField(blank=True, upload_to='tours/static/banners/'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(upload_to='tours/static/destinations/'),
        ),
    ]
