# Generated by Django 4.1.5 on 2023-03-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_tour_banner_alter_destination_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(upload_to='static/tour/destinations/'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='banner',
            field=models.ImageField(blank=True, upload_to='static/tours/banners/'),
        ),
    ]
