# Generated by Django 4.1.5 on 2023-03-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0003_remove_seatallocation_seat_coachallocation_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachallocation',
            name='seat',
        ),
        migrations.AddField(
            model_name='seatallocation',
            name='seat',
            field=models.ManyToManyField(to='train.seat'),
        ),
    ]
