# Generated by Django 4.1.5 on 2023-06-13 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="DaySchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_number", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=500)),
                (
                    "activities",
                    models.ManyToManyField(
                        related_name="activities", to="vacation_package.activity"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inclusions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("overview", models.CharField(max_length=200, null=True)),
                ("price", models.IntegerField()),
                (
                    "days",
                    models.ManyToManyField(
                        related_name="days", to="vacation_package.dayschedule"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Photos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="static/package/images")),
            ],
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Things",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thing", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=1000)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vacation_package.photos",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Package_Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("children", models.IntegerField()),
                ("Adult", models.IntegerField()),
                ("date_booked", models.DateField()),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vacation_package.package",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="package",
            name="exclusions_things",
            field=models.ManyToManyField(
                related_name="exclusions_things", to="vacation_package.things"
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="images",
            field=models.ManyToManyField(
                related_name="images", to="vacation_package.photos"
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="inclusions",
            field=models.ManyToManyField(
                related_name="inclusion", to="vacation_package.inclusions"
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="inclusions_things",
            field=models.ManyToManyField(
                related_name="inclusions_things", to="vacation_package.things"
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="vacation_package.place"
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="themes",
            field=models.ManyToManyField(
                related_name="themes", to="vacation_package.theme"
            ),
        ),
        migrations.CreateModel(
            name="Month",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "packages",
                    models.ManyToManyField(
                        related_name="packages", to="vacation_package.package"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("stars", models.IntegerField()),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vacation_package.place",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dayschedule",
            name="hotel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="vacation_package.hotel"
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="inclusion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="vacation_package.inclusions",
            ),
        ),
    ]
