# Generated by Django 4.1.5 on 2023-06-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacation_package", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="month",
            name="packages",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="packages",
                to="vacation_package.package",
            ),
        ),
    ]
