# Generated by Django 4.1.5 on 2023-06-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacation_package", "0002_alter_month_packages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dayschedule",
            name="description",
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name="place",
            name="description",
            field=models.CharField(max_length=5000),
        ),
    ]
