# Generated by Django 4.1.5 on 2023-06-14 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vacation_package", "0003_alter_dayschedule_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="package",
            name="images",
        ),
    ]
