# Generated by Django 4.1.5 on 2023-06-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacation_package", "0004_remove_package_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="images_folder",
            field=models.IntegerField(null=True),
        ),
    ]
