# Generated by Django 4.1.5 on 2023-07-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacation_package", "0005_package_images_folder"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="total_images",
            field=models.IntegerField(null=True),
        ),
    ]
