# Generated by Django 4.1.5 on 2023-07-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacation_package", "0006_package_total_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="overview",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
