# Generated by Django 4.1.5 on 2023-03-08 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_id',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='bus_id',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='seat_id',
        ),
    ]
