# Generated by Django 4.1.5 on 2023-03-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0003_bus_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='price',
            field=models.IntegerField(),
        ),
    ]
